#!/tmp/bootimgtools/tools/bash
tooldir=/tmp/bootimgtools/tools
box=$tooldir/busybox

# fixes a bug
cd $tooldir/kernel/
$box tar -zxf ramdisk.tar.gz
$box rm ramdisk.tar.gz

# system goes too fast, so we need to slow it down
sleep 2
